apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared
          emptyDir: {}
      containers:
        - name: logoutput-writer
          image: yasder/logoutput:storage110
          volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files
        - name: logoutput-response
          image: yasder/logoutput:storage110response
          volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files
#
